kmfoundation/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "KM FOUNDATION Administration"
admin.site.site_title = "KM FOUNDATION Admin Portal"
admin.site.index_title = "Welcome to KM FOUNDATION Admin Portal"

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("course-list/<str:id>", views.courseList, name="course-list"),
    path("course-detail/", views.courseDetail, name="course-detail"),
    path("updates/", views.updates, name="updates"),
    path("update-detail/<str:id>", views.update_detail, name="update-detail"),
    path("event/", views.event, name="event"),
    path("event-detail/<str:id>", views.event_detail, name="event-detail"),
    path("university/<str:id>", views.university, name="university"),
    path("university-detail/<str:id>", views.university_detail, name="university-detail"),
    path("contact/", views.contact, name="contact"),
    path("service/<str:id>", views.service, name="service"),
    path("service-detail/<str:id>", views.service_detail, name="service-detail"),

    path("career/", views.career, name="career"),
    path("career-detail/<str:id>", views.career_detail, name="career-detail"),


    path("domestic/", views.domestic, name="domestic"),
    path("international", views.international, name="international"),

]

templates/web/blog-details.html
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

templates/web/blog.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<div class="inner-banner inner-banner-bg4">
    <div class="container">
        <div class="inner-title text-center">
            <h3>Blog grid</h3>
            <ul>
                <li>
                    <a href="index.html">Home</a>
                </li>
                <li>Blog grid</li>
            </ul>
        </div>
    </div>
</div>


<div class="blog-area pt-100 pb-70">
    <div class="container">
        <div class="row align-items-center mb-45">
            <div class="col-lg-8 col-md-9">
                <div class="section-title mt-rs-20">
                    <h2>Latest from our blogs</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                        labore et dolore.
                    </p>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            {% for blog in blog %}

            <div class="col-lg-4 col-md-6">
                <div class="blog-card">
                    <a href="{% url 'web:blog-detail' %}">
                        <img src="{{ blog.image.url }}" alt="Blog">
                    </a>
                    <div class="content">
                        <ul>
                            <li><i class="ri-calendar-todo-fill"></i> {{ blog.date }} </li>
                            <li><i class="ri-price-tag-3-fill"></i> <a href="tags.html">Education</a></li>
                        </ul>
                        <h3><a href="{% url 'web:blog-detail' %}">{{ blog.blog_heading}}</a></h3>
                        <p>{{ blog.about_blog|safe }}</p>
                        <a href="{% url 'web:blog-detail' %}" class="read-btn">Read More</a>
                    </div>
                </div>
            </div>

            {% endfor %}

            <div class="col-lg-12 col-md-12 text-center">
                <div class="pagination-area">
                    <a href="blog.html" class="prev page-numbers">
                        <i class="flaticon-left-arrow"></i>
                    </a>
                    <span class="page-numbers current" aria-current="page">1</span>
                    <a href="blog.html" class="page-numbers">2</a>
                    <a href="blog.html" class="page-numbers">3</a>
                    <a href="blog.html" class="next page-numbers">
                        <i class="flaticon-chevron"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="newsletter-area section-bg ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="section-title mt-rs-20">
                    <span>ARE YOU IMPRESSED FOR AMAZING SERVICES?</span>
                    <h2>Subscribe our newsletter</h2>
                </div>
            </div>
            <div class="col-lg-7">
                <form class="newsletter-form" data-toggle="validator" method="POST">
                    <input type="email" class="form-control" placeholder="Enter Your Email Address" name="EMAIL"
                        required autocomplete="off">
                    <button class="subscribe-btn" type="submit">
                        Subscribe Now <i class="flaticon-paper-plane"></i>
                    </button>
                    <div id="validator-newsletter" class="form-result"></div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/web/event-details.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<div class="event-details-area pt-50 pb-70">
<div class="container">
    <div class="section-title text-center mb-45">
        <span>Event</span>
        <h2>{{ event.event_name}}</h2>
    </div>
<div class="row justify-content-center">
<div class="col-lg-8">
<div class="event-details-content pr-20">
<div class="event-preview-img text-center">
<img src="{{ event.image.url }}" alt="Event Details">
</div>
<!-- <h2>{{ event.event_name}}</h2> -->


<div class="event-sidebar">
    <h3 class="title">Events description</h3>
    <ul>
    <li>Location: <span>{{ event.location}}</span></li>
    <li>Date: <span>{{ event.date}}</span></li>
    <li>Time: <span>{{ event.time}}</span></li>
    <li>Phone: <span>011-325-143-2567</span></li>
    <li>map: <span> <a href="{{ event.map_link}}">
        {{ event.map_link}}
    </a></span> </li>

    </ul>
    </div>
<p>
    {{ event.about_event|safe}}
</p>





</div>
</div>

</div>
</div>
</div>


{% endblock %}

templates/web/event.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<div class="event-area pt-50 pb-100">
    <div class="container">
        <div class="section-title text-center mb-45">
            <span>EVENT</span>
            <h2>Our Awesome Upcoming Events</h2>
        </div>
        <div class="row">

            {% for event in event %}
            <div class="col-lg-6">
                <div class="event-item box-shadow">
                    <div class="event-img">
                        <a href="{% url 'web:event-detail' event.id %}">
                            <img src="{{ event.image.url }}" alt="Events" />
                        </a>
                    </div>
                    <div class="event-content">
                        <ul class="event-list">
                            <li><i class="ri-calendar-todo-fill"></i>{{ event.date }}</li>
                            <li><i class="ri-map-pin-fill"></i>{{ event.location }}</li>
                            <li><i class="ri-time-fill"></i> {{ event.time }}</li>
                        </ul>
                        <h3><a href="{% url 'web:event-detail' event.id %}">{{ event.event_name }}</a></h3>
                        <p>{{ event.about_event|safe|truncatechars:200 }}</p>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>


{% endblock %}

templates/web/test.html
hiiiiiiiii

templates/web/university-detail.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<div class="blog-details-area pt-100 pb-70">
    <div class="container">
        <div class="section-title text-center mb-45">
            <span>University Detail</span>
            <h2>{{university.name}}</h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="blog-details-content pr-20">
                    <div class="blog-preview-slider owl-carousel owl-theme owl-loaded owl-drag">
                        <div class="owl-dots disabled"></div>
                    </div>

                    <p>
                        {{ university.about|safe}}
                    </p>
                    <div class="pb-3" style="text-align: center;">
                        <a href="#apply" class="d-lg-none default-btn">
                            Apply
                            </a>
                    </div>

                    <div class="article-share">
                        <h1>
                            Courses offerd
                        </h1>
                        {% for c in university.getcouses %}
                        <div class="row align-items-center">
                            <div class="col-lg-6 col-md-6">
                                <div class="article-tag">
                                    <ul>


                                        <li class="title"><i class="ri-price-tag-3-fill"></i></li>

                                        <li><a href="" target="_blank">{{c.course_type.course_name}}</a></li>




                                    </ul>
                                </div>
                            </div>

                        </div>


                        {% endfor %}

                    </div>

                </div>
            </div>

            <div class="col-lg-4" id="apply">
                <div class="contact-form" >
                    <form method="post" id="whatsappform">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <input type="text" id="name" name="name" class="form-control" required=""
                                        data-error="Please Enter Your Name" placeholder="Name">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <input type="email" id="email" name="email" class="form-control" required=""
                                        data-error="Please Enter Your Email" placeholder="Email">
                                </div>
                            </div>
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <input type="text" id="phone" name="phone" required=""
                                        data-error="Please Enter Your number" class="form-control"
                                        placeholder="Phone Number">
                                </div>
                            </div>

                            <div class="col-lg-12">
                                <div class="form-group">
                                    <select name="course" id="course" class="form-control">
                                        <option value="">Choose course....</option>
                                        {% for course in university.getcouses %}
                                        <option value="{{course.course_type.course_name}}">
                                            {{course.course_type.course_name}}</option>
                                        {% endfor %}


                                    </select>
                                </div>
                                <input type="text" hidden id="university" value="{{university.name}}">
                            </div>


                            <div class="col-lg-12 col-md-12">

                                <button type="submit" class="default-btn" style="pointer-events: all; cursor: pointer;">
                                    Apply Now
                                </button>


                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>


{% endblock %}

{% block js %}



<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>

<script>
    $("#whatsappform").validate({
        submitHandler: function (form) {
            // const form = $("#whatsappform");
            // const to_phone = '918547768153';
            const name = $("#name").val();
            const email = $("#email").val();
            const phone = $("#phone").val();
            const course = $("#course").val();
            const university = $("#university").val();

            const text = [
                'name:' + name,
                'email:' + email,
                'phone:' + phone,
                'course: ' + course,
                'university: ' + university,


            ].join("\n") // change to what you want sep to be

            // make the url
            const action = "https://wa.me/918848804339" + "?text=" + encodeURIComponent(text);
            window.location.href = action;

        }
    });
</script>
{% endblock %}

templates/web/university.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<div class="event-area pt-100 pb-100">
    <div class="container">
        <div class="section-title text-center mb-45">
            <span>University</span>
            <h2>Boost Your Career From Top-Rated Universities</h2>
        </div>
        <div class="row">

            {% for i in university %}
            <div class="col-lg-6">
                <div class="event-item box-shadow">
                    <div class="event-img">
                        <a href="{% url 'web:university-detail' i.id %}">
                            <img src="{{ i.images.url }}" alt="Events">
                        </a>
                    </div>
                    <div class="event-content">

                        <h3><a href="{% url 'web:university-detail' i.id  %}">{{ i.name }}</a></h3>
            
                        <p>{{ i.about|safe|truncatechars:200 }}</p>
            
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

templates/web/updates.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<div class="blog-area pt-50  pb-70">
    <div class="container">
        <div class="section-title text-center mb-45">
            <span>UPDATE</span>
            <h2>Get updated with our latest news and blogs</h2>
        </div>
        <div class="row">
            {% for blog in blog %}

            <div class="col-lg-3 col-md-6">
                <div class="blog-card">
                    <a href="{% url 'web:update-detail' blog.id %}">
                        <img src="{{ blog.image.url }}" alt="Blog">
                    </a>
                    <div class="content">
                        <ul>
                            <li><i class="ri-calendar-todo-fill"></i> {{ blog.date }} </li>
                        </ul>
                        <h3><a href="{% url 'web:update-detail' blog.id %}">{{ blog.blog_heading}}</a></h3>
                        <p>{{ blog.about_blog|safe|truncatechars:200 }}</p>
                        <a href="{% url 'web:update-detail' blog.id %}" class="read-btn">Read More</a>
                    </div>
                </div>
            </div>

            {% endfor %}


        </div>
    </div>
</div>


{% endblock %}