kmfoundation/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("web.urls", namespace="web")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "KM FOUNDATION Administration"
admin.site.site_title = "KM FOUNDATION Admin Portal"
admin.site.index_title = "Welcome to KM FOUNDATION Admin Portal"

web/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("course-list/<str:id>", views.courseList, name="course-list"),
    path("course-detail/", views.courseDetail, name="course-detail"),
    path("updates/", views.updates, name="updates"),
    path("update-detail/<str:id>", views.update_detail, name="update-detail"),
    path("event/", views.event, name="event"),
    path("event-detail/<str:id>", views.event_detail, name="event-detail"),
    path("university/<str:id>", views.university, name="university"),
    path("university-detail/<str:id>", views.university_detail, name="university-detail"),
    path("contact/", views.contact, name="contact"),
    path("service/<str:id>", views.service, name="service"),
    path("service-detail/<str:id>", views.service_detail, name="service-detail"),

    path("career/", views.career, name="career"),
    path("career-detail/<str:id>", views.career_detail, name="career-detail"),


    path("domestic/", views.domestic, name="domestic"),
    path("international", views.international, name="international"),

]

templates/web/partials/base.html
{% load static %}
<!doctype html>
<html lang="zxx">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'web/css/plugins.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/iconplugins.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/responsive.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/theme-dark.css' %}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <title>KM Foundation</title>

    <link rel="icon" type="image/png" href="{% static 'web/images/km-icon.png' %}">
</head>

<body>
    
    <!-- <div id="preloader">
        <div id="preloader-area">
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
            <div class="spinner"></div>
        </div>
        <div class="preloader-section preloader-left"></div>
        <div class="preloader-section preloader-right"></div>
    </div> -->


<!-- header & nav  -->

{% include 'web/partials/header.html' %}


<!-- content -->
{% block content %}

{% endblock %}


<!-- footer -->
{% include 'web/partials/footer.html' %}



    <script src="{% static 'web/js/jquery.min.js' %}"></script>

    <script src="{% static 'web/js/plugins.js' %}"></script>


    {% block js %}

{% endblock %}


    <script src="{% static 'web/js/custom.js' %}"></script>

    <script src="//code.tidio.co/hp53efgdlo7zkszipalgd4m3co6k4bio.js" async></script>


</body>

</html>

templates/web/partials/footer.html
{% load static %}

<footer class="footer-area">
    <div class="container pt-100">
        <div class="row">
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget">
                    <div class="footer-logo">
                        <a href="index.html">
                            <img src="{% static 'web/images/logos/kmwhite.png' %}" alt="Images" loading="lazy">
                        </a>
                    </div>
                    <p>
                        K M Foundation is one of the most trusted educational organizations in India delivering quality career assistance for aspirants.
                    </p>
                    <ul class="social-link">
                        <li class="social-title">Follow Us:</li>
                        <li>
                            <a href="https://www.facebook.com/" target="_blank">
                                <i class="ri-facebook-fill"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/" target="_blank">
                                <i class="ri-twitter-fill"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.pinterest.com/" target="_blank">
                                <i class="ri-instagram-line"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-sm-6">
                <div class="footer-widget ps-5">
                    <h3>Quick Links</h3>
                    <ul class="footer-list">
                        <li>
                            <a href="{% url 'web:index' %}">
                                Home
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'web:about' %}">
                                About
                            </a>
                        </li>

                        <li>
                            <a href="#course" >
                                Course
                            </a>
                        </li>



                        <li>
                            <a href="">
                                Service
                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>

            <div class="col-lg-6 col-sm-6">
                <div class="footer-widget ps-5">
                    <h3>Official Info</h3>
                    <ul class="footer-contact">
                        <li>
                            <i class="ri-map-pin-2-fill"></i>
                            <div class="content">
                                <h4>Location:</h4>
                                <span>Address: 2nd Floor, Forza Mall2, Chembra Road,
                                    Near Gulf market Tirur, Malappuram Dt - 676101, Kerala, India</span>
                            </div>
                        </li>
                        <li>
                            <i class="ri-mail-fill"></i>
                            <div class="content">
                                <h4>Email:</h4>
                                <span><a
                                        href="mailto: infokmfoundation@gmail.com"><span>infokmfoundation@gmail.com</span></a></span>
                            </div>
                        </li>
                        <li>
                            <i class="ri-phone-fill"></i>
                            <div class="content">
                                <h4>Phone:</h4>
                                <span><a href="tel:918848804339">+91 8848804339</a></span>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-area">
        <div class="container">
            <div class="copy-right-text text-center">
                <p>
                    Copyright @
                    <script data-cfasync="false"
                        src="../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear())</script> <b> Kmfoundation</b> 
    
                </p>
            </div>
        </div>
    </div>
</footer>

templates/web/partials/header.html
{% load static %}

<header class="top-header">
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-lg-9 col-md-8">
                <div class="header-left">
                    <ul>
                        <li>
                            <i class="ri-phone-fill"></i>
                            <a href="tel:918848804339">+91 8848804339</a>
                        </li>
                        <li>
                            <i class="ri-mail-fill"></i>
                            <a href="mailto: infokmfoundation@gmail.com"><span>infokmfoundation@gmail.com</span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-4">
                <div class="header-right">
                    <div class="header-language dropdown language-option">

                    </div>
                    <ul class="social-list">
                        <li>
                            <a href="https://www.facebook.com/" target="_blank">
                                <i class="ri-facebook-fill"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/" target="_blank">
                                <i class="ri-twitter-fill"></i>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.pinterest.com/" target="_blank">
                                <i class="ri-instagram-line"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>


<div class="navbar-area">
    <div class="mobile-responsive-nav">
        <div class="container">
            <div class="mobile-responsive-menu">
                <div class="logo">
                    <a href="{% url 'web:index' %}">
                        <img src="{% static 'web/images/logos/km.svg' %}" class="logo-one phone-svg" alt="logo">
                        <img src="{% static 'web/images/logos/km.svg' %}" class="logo-two" alt="logo">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="desktop-nav nav-area shadow-sm">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-light ">
                <a class="navbar-brand" href="{% url 'web:index' %}">
                    <img src="{% static 'web/images/logos/km.svg' %}" class="logo-one svg-logo" alt="Logo">
                    <img src="{% static 'web/images/logos/km.svg' %}" class="logo-two" alt="Logo">
                </a>

                {% comment %}
                <div class="nav-widget-form">
                    <form class="search-form search-form-bg">
                        <input type="search" class="form-control" placeholder="Search courses">
                        <button type="submit">
                            <i class="ri-search-line"></i>
                        </button>
                    </form>
                </div>
                {% endcomment %}




                <div class="collapse navbar-collapse mean-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a href="{% url 'web:index' %}" class="nav-link {% if is_index %}active{% endif %}">
                                Home
                            </a>
                        </li>


                        <li class="nav-item">
                            <a href="{% url 'web:about' %}" class="nav-link {% if is_about %}active{% endif %}">
                                About Us
                            </a>
                        </li>


                        <li class="nav-item">
                            <a href="#" class="nav-link dropdown-toggle">
                                Courses
                            </a>
                            <ul class="dropdown-menu">
                                <li class="nav-item">
                                    <a href="{% url 'web:domestic'  %}" class="nav-link">Domestic</a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'web:international' %}" class="nav-link">International</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a href="#" class="nav-link dropdown-toggle">
                                Services
                            </a>
                            <ul class="dropdown-menu">

                                {% for catagory in service_catagory %}
                                <li class="nav-item">
                                    <a href="{% url 'web:service' catagory.id %}" class="nav-link">{{ catagory.service_catagory }}</a>
                                </li>
                                {% endfor %}
                        </li>
                    </ul>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'web:updates' %}" class="nav-link {% if is_blog %}active{% endif %}">
                            Updates
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'web:event' %}" class="nav-link {% if is_event %}active{% endif %}">
                            Events
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'web:career' %}" class="nav-link {% if is_career %}active{% endif %}">
                            Careers
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{% url 'web:contact' %}" class="nav-link {% if is_contact %}active{% endif %}">
                            Contact Us
                        </a>
                    </li>

                    <li class="nav-item">
                        <div class="switch-box"><label id="switch" class="switch"><input type="checkbox"
                                    onchange="toggleTheme()" id="slider"><span class="slider round"></span></label>
                        </div>
                    </li>

                    </ul>

                    {% comment %}
                    <div class="others-options d-flex align-items-center">
                        <div class="optional-item">
                            <a href="signup.html" class="default-btn two border-radius-50">Sign Up</a>
                        </div>
                    </div>

                    {% endcomment %}

                </div>
            </nav>
        </div>
    </div>

</div>